# Generated by Django 5.2.1 on 2025-06-08 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hms_operator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('prescribed_medicines', models.TextField(help_text='Separate multiple medicines with commas')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('report_time', models.TimeField(auto_now_add=True)),
                ('doctor_name', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hms_operator.patient')),
            ],
        ),
    ]
