# Generated by Django 5.2.1 on 2025-06-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')])),
                ('region', models.CharField(choices=[('malir', 'Malir'), ('korangi', 'Korangi'), ('Defense', 'defense'), ('Bhens Colony', 'bhens colony'), ('Quaidabad', 'quaidabad'), ('sadar', 'Sadar')], max_length=20)),
                ('prefered_doctor', models.CharField(choices=[('Dr. Moosa', 'Dr. Moosa'), ('Dr. Fareed', 'Dr. Fareed'), ('Dr. Umair', 'Dr. Umair')], max_length=20)),
                ('cnic', models.CharField(max_length=13)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
